### ISSUE TITLE
Support Relay connections

### ISSUE THREAD

**Issue by rubenfonseca** [ontohub/graphql-pundit#35]
Right now when I use the `connection` method to define a Relay connection with GraphQL, the `scope` method doesn't work properly. It is initialised with the current_user and the current type, not the scope.

Is this to be expected? I was expecting the resolve function of my scope to be passed my ActiveRecord::Relation or Mongoid::Criteria.

**Comment by phyrog** [comment]
Thank you for reporting this. This Gem is currently completely untested when it comes to Relay (since we don't use Relay), but I'll have a look at fixing it; it certainly sounds like a bug.

**Comment by phyrog** [comment]
Okay, so after thinking this over for a bit, I believe the current behavior is intended, but not very useful at the moment.

The reason for that is that `scope` is basically just a before-hook for `resolve`. Since `resolve` is the function that normally plucks the fields from an object, `scope` can't know what the field value is.

Now, what you want is something like `scope_after`, that runs after `resolve`, which in retrospect seems much more useful than the current `scope`.

However, since changing the behavior of `scope` would be a pretty big breaking change, I'd opt for adding `scope_after` alongside `scope` (which might be renamed to `scope_before` with a backwards compatible alias `scope`).

**Comment by phyrog** [comment]
@rubenfonseca I pushed a branch that changes `scope` to being run after `resolve`. Could you try it out to see if `scope` now fits your use case better?

```ruby
# Gemfile

gem 'graphql-pundit', github: 'ontohub/graphql-pundit',
                      branch: '35-support_relay_connections'
```

**Comment by rubenfonseca** [comment]
Thanks so much for your work, this is working very good!! But I can't imagine you pushing this into master since it will break all the people using your gem, right?

**Comment by phyrog** [comment]
I think there is not much harm in releasing this change. Not many people are using this Gem as of yet, plus we're still in the sub-1.0 version range, so breaking changes are to be expected. The question is however, if this will make any current use-cases impossible.

@eugenk do you have an opinion on this? Running `scope` after `resolve` makes much more sense IMO.

**Comment by eugenk** [comment]
Sorry for the delayed answer. I've got a lot on my plate right now.

This is a tricky question. I think there are use cases for both `scope_before` and `scope_after`. 

The problem with `scope_after` is that `resolve` will (possibly computationally expensively) process data of which most data is thrown away afterwards. Also, scoping might become more expensive. See, for example, [Types::OrganizationalUnitType](https://github.com/ontohub/ontohub-backend/blob/50a22a10c92c465c4c5381d3e8cf6d755894f2b3/app/graphql/types/organizational_unit_type.rb#L30-L40) with [RepositoryPolicy::Scope](https://github.com/ontohub/ontohub-backend/blob/50a22a10c92c465c4c5381d3e8cf6d755894f2b3/app/policies/repository_policy.rb#L7-L23). If we were to change this to a `scope_after`, we would need to return a `Sequel::Dataset` in `resolve` to keep a higher performance, but we return an `Array` and I don't see how to not convert that into an `Array`.

On the other hand, `scope_before` sometimes cannot know the data that is scoped. So there are valid use cases for both of them.
